import './style.css';
import { VidraEngine } from '@sansavision/vidra-player';

// --- Tab Logic ---
const tabs = document.querySelectorAll('.tab-btn');
const contents = document.querySelectorAll('.tab-content');

tabs.forEach(tab => {
    tab.addEventListener('click', () => {
        // Remove active class
        tabs.forEach(t => t.classList.remove('active'));
        contents.forEach(c => c.classList.remove('active'));
        
        // Add active class
        tab.classList.add('active');
        document.getElementById(tab.dataset.tab).classList.add('active');
    });
});

// --- Output IR & Player Logic ---
const irOutput = document.getElementById('ir-output');
let engine;
let isPlaying = false;
let irJSON = "{}";

const playBtn = document.getElementById('play-btn');
const pauseBtn = document.getElementById('pause-btn');
const restartBtn = document.getElementById('restart-btn');
const timeDisplay = document.getElementById('time-display');
const canvas = document.getElementById('vidra-canvas');

async function initPlayer() {
    try {
        // Fetch the built project JSON
        const res = await fetch('/project.json');
        if (!res.ok) throw new Error("Could not find project.json. Did you run 'npm run build:video'?");
        
        irJSON = await res.text();
        
        // Output IR
        try {
             irOutput.textContent = JSON.stringify(JSON.parse(irJSON), null, 2);
        } catch {
             irOutput.textContent = irJSON;
        }

        // Initialize the WASM engine
        engine = new VidraEngine(canvas);
        
        // Load the JSON IR generated by the SDK
        engine.load_project(irJSON);
        
        // Start the render loop
        requestAnimationFrame(renderLoop);
        
        // Start playback by default
        engine.play();
        isPlaying = true;
        updateControls();
    } catch (err) {
        console.error("Failed to initialize VidraEngine:", err);
        timeDisplay.textContent = "Error loading WASM";
        irOutput.textContent = err.message;
    }
}

function renderLoop() {
    if (!engine) return;
    
    // Have the engine render the current frame if it's playing
    engine.render();
    
    // Update the time display
    const time = engine.get_time();
    timeDisplay.textContent = time.toFixed(2) + 's';
    
    requestAnimationFrame(renderLoop);
}

function updateControls() {
    playBtn.classList.toggle('active', isPlaying);
    pauseBtn.classList.toggle('active', !isPlaying);
}

playBtn.addEventListener('click', () => {
    if (engine) {
        engine.play();
        isPlaying = true;
        updateControls();
    }
});

pauseBtn.addEventListener('click', () => {
    if (engine) {
        engine.pause();
        isPlaying = false;
        updateControls();
    }
});

restartBtn.addEventListener('click', () => {
    if (engine) {
        engine.seek(0);
        engine.play();
        isPlaying = true;
        updateControls();
    }
});

// Start player when DOM loads
initPlayer();
