import './style.css';
import { VidraEngine } from '@sansavision/vidra-player';

// --- Tab Logic ---
const tabs = document.querySelectorAll('.tab-btn');
const contents = document.querySelectorAll('.tab-content');

tabs.forEach(tab => {
    tab.addEventListener('click', () => {
        // Remove active class
        tabs.forEach(t => t.classList.remove('active'));
        contents.forEach(c => c.classList.remove('active'));

        // Add active class
        tab.classList.add('active');
        const targetId = (tab as HTMLElement).dataset.tab;
        if (targetId) {
            document.getElementById(targetId)!.classList.add('active');
        }
    });
});

// --- Output IR & Player Logic ---
const irOutput = document.getElementById('ir-output') as HTMLPreElement;
let engine: VidraEngine | null = null;
let isPlaying = false;
let irJSON = "{}";

const playBtn = document.getElementById('play-btn') as HTMLButtonElement;
const pauseBtn = document.getElementById('pause-btn') as HTMLButtonElement;
const restartBtn = document.getElementById('restart-btn') as HTMLButtonElement;
const timeDisplay = document.getElementById('time-display') as HTMLSpanElement;
const canvas = document.getElementById('vidra-canvas') as HTMLCanvasElement;

async function initPlayer() {
    try {
        // Fetch the built project JSON
        const res = await fetch('/project.json');
        if (!res.ok) throw new Error("Could not find project.json. Did you run 'npm run build:video'?");

        irJSON = await res.text();

        // Output IR
        try {
            irOutput.textContent = JSON.stringify(JSON.parse(irJSON), null, 2);
        } catch {
            irOutput.textContent = irJSON;
        }

        // Initialize the WASM engine
        engine = new VidraEngine(canvas);
        await engine.init();

        // Load the JSON IR generated by the SDK
        engine.loadIR(irJSON);

        // Start the render loop
        requestAnimationFrame(renderLoop);

        // Start playback by default
        engine.play();
        isPlaying = true;
        updateControls();
    } catch (err: any) {
        console.error("Failed to initialize VidraEngine:", err);
        timeDisplay.textContent = "Error loading WASM";
        irOutput.textContent = err.message;
    }
}

function renderLoop() {
    if (!engine) return;

    // Have the engine render the current frame if it's playing
    engine.renderCurrentFrame();

    // Update the time display
    const time = engine.getCurrentTime();
    timeDisplay.textContent = time.toFixed(2) + 's';

    requestAnimationFrame(renderLoop);
}

function updateControls() {
    playBtn.classList.toggle('active', isPlaying);
    pauseBtn.classList.toggle('active', !isPlaying);
}

playBtn.addEventListener('click', () => {
    if (engine) {
        engine.play();
        isPlaying = true;
        updateControls();
    }
});

pauseBtn.addEventListener('click', () => {
    if (engine) {
        engine.pause();
        isPlaying = false;
        updateControls();
    }
});

restartBtn.addEventListener('click', () => {
    if (engine) {
        engine.seekToFrame(0);
        engine.play();
        isPlaying = true;
        updateControls();
    }
});

// Start player when DOM loads
initPlayer();
