import { useState } from 'react';
import { Bot, Send, Sparkles, Command } from 'lucide-react';

export default function AIChatPanel() {
    const [messages, setMessages] = useState<{ role: 'user' | 'ai', content: string }[]>([
        {
            role: 'ai',
            content: "Hi! I'm Vidra AI. I can generate TypeScript code using `@sansavision/vidra-sdk`. Describe the video you want to build!"
        }
    ]);
    const [input, setInput] = useState('');

    const handleSend = () => {
        if (!input.trim()) return;
        setMessages(prev => [...prev, { role: 'user', content: input }]);
        setInput('');

        // Mock AI response
        setTimeout(() => {
            setMessages(prev => [...prev, {
                role: 'ai',
                content: `I can certainly help with that. Try adding this layer to your \`src/video.ts\` scene:\n\n\`\`\`ts\n.addLayer(\n  new Layer("ai_layer")\n    .text("Generated by AI!", "Inter", 48, "#d2a8ff")\n    .position(960, 540)\n    .animate("opacity", 0, 1, 1, Easing.EaseOut)\n)\n\`\`\`\n\nRun \`npm run build:video\` to apply!`
            }]);
        }, 1200);
    };

    return (
        <div className="flex flex-col h-full bg-[#161b22] border-l border-vd-border">
            <div className="p-4 border-b border-vd-border flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-vd-accent" />
                <h3 className="font-semibold">Vidra Intelligence</h3>
            </div>

            <div className="flex-1 overflow-y-auto p-4 space-y-4">
                {messages.map((m, i) => (
                    <div key={i} className={`flex gap-3 text-sm ${m.role === 'user' ? 'flex-row-reverse' : ''}`}>
                        <div className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${m.role === 'user' ? 'bg-[#238636]' : 'bg-[#1f6feb]'}`}>
                            {m.role === 'user' ? <Command className="w-4 h-4 text-white" /> : <Bot className="w-4 h-4 text-white" />}
                        </div>
                        <div className={`p-3 rounded-xl max-w-[85%] ${m.role === 'user' ? 'bg-[#238636]/20 border border-[#238636]/30 text-white' : 'bg-[#0d1117] border border-vd-border text-vd-dim'}`}>
                            <pre className="whitespace-pre-wrap font-sans leading-relaxed">{m.content}</pre>
                        </div>
                    </div>
                ))}
            </div>

            <div className="p-4 border-t border-vd-border bg-[#0d1117]">
                <div className="flex items-center bg-[#161b22] rounded-lg border border-vd-border focus-within:border-vd-accent transition-colors">
                    <input
                        type="text"
                        className="flex-1 bg-transparent border-none outline-none p-3 text-sm text-white placeholder-vd-dim"
                        placeholder="Generate a video scene..."
                        value={input}
                        onChange={e => setInput(e.target.value)}
                        onKeyDown={e => e.key === 'Enter' && handleSend()}
                    />
                    <button
                        onClick={handleSend}
                        className="p-3 text-vd-dim hover:text-vd-accent transition-colors"
                    >
                        <Send className="w-4 h-4" />
                    </button>
                </div>
                <p className="text-center text-[10px] text-vd-dim mt-2 tracking-wide">Bring your own API key in production.</p>
            </div>
        </div>
    );
}
